spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

logging:
  level:
    org:
      springframework:
        security: trace

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem


sentry:
  dsn: https://9b8f2f5dbcbc45075cb07dd618f7024a@o4508415448383488.ingest.de.sentry.io/4508415461163088
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647
