spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

logging:
  level:
    org:
      springframework:
        security: trace

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem